import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer } from "@/components/footer";
import { Arrow, Mark } from "@/components/icons";
import { projects } from "@/data/projects";
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const project = projects.find(p => p.slug === slug); return project ? { title: project.title, description: project.description } : {}; }); }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find(p => p.slug === slug); if (!project) notFound(); return <><header className="nav"><Link href="/" className="brand"><Mark /> YASH<span>STUDIO</span></Link><Link href="/#work" className="back">← Back to work</Link></header><main className="project-page"><span className="section-label">{project.category}</span><h1>{project.title}</h1><p className="project-lead">{project.description}</p><div className={`detail-visual ${project.accent}`}><div><span>PROJECT / {project.slug.toUpperCase()}</span><strong>{project.title}</strong></div></div><div className="case-study"><aside><span>Overview</span><span>Approach</span><span>Details</span></aside><div><section><h2>The challenge</h2><p>{project.problem}</p></section><section><h2>The approach</h2><p>{project.solution}</p></section><section><h2>Key functionality</h2><ul>{project.features.map(f => <li key={f}>{f}</li>)}</ul></section><section><h2>Technology</h2><div className="tags">{project.technologies.map(t => <span key={t}>{t}</span>)}</div></section><p className="placeholder-note">This is a portfolio placeholder project. Replace the description, preview, URLs, and details with work you are able to share publicly.</p></div></div><section className="next-project"><p>Have a similar challenge?</p><Link className="text-link" href="/#contact">Start a conversation <Arrow /></Link></section></main><Footer /></>; }
