import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Arrow } from "@/components/icons";
import { ContactForm } from "@/components/contact-form";
import { ScrollEffects } from "@/components/scroll-effects";
import { WorkShowcase } from "@/components/work-showcase";

const services = [["Websites", "Professional websites for businesses, professionals, and brands."], ["Web applications", "Custom applications for bookings, dashboards, workflows, and customer experiences."], ["E-commerce", "Online stores designed around products, customers, and sales."], ["Custom software", "Purpose-built tools for processes that need more than an off-the-shelf solution."], ["APIs & integrations", "Connect your website and applications with payments, APIs, and the services you already use."], ["IT & cloud", "Practical deployment and technical support when your project needs it."]];

export default function Home() { const jsonLd = { "@context": "https://schema.org", "@type": "ProfessionalService", name: "Yash Studio", description: "Website, web application, and custom software development for businesses.", email: "hello@your-domain.com", areaServed: "Worldwide" };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Navbar /><main className="business-home"><ScrollEffects />
    <section className="business-hero"><div className="hero-main" data-reveal><span className="kicker">Freelance web & software developer</span><h1>Websites &amp; software <span>built for your business.</span></h1><p>I design and develop modern websites, web applications, and custom digital solutions that are fast, practical, and easy to use.</p><div className="hero-actions"><a href="#contact" className="button button-dark">Start a project <span>→</span></a><a href="#work" className="text-link">View my work <Arrow /></a></div></div><div className="hero-product" data-reveal><div className="hero-window"><div className="window-top"><i /><i /><i /><span>project overview</span></div><div className="window-main"><small>BUILD WITH CONFIDENCE</small><h2>Clear digital<br />solutions for<br /><em>real businesses.</em></h2><div><b>Website</b><b>Application</b><b>Software</b></div></div></div><div className="hero-float"><span>01</span><b>Strategy → build → launch</b></div></div></section>
    <section className="capability-strip" aria-label="Core capabilities"><span>Websites</span><i>·</i><span>Web apps</span><i>·</i><span>E-commerce</span><i>·</i><span>Custom software</span></section>
    <WorkShowcase />
    <section id="services" className="build-section" data-reveal><div className="section-heading"><div><span className="kicker">Services</span><h2>What I <em>build.</em></h2></div><p>Clear, modern digital products that help your business look professional, work better, and grow with confidence.</p></div><div className="build-grid">{services.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p><a href="#contact" aria-label={`Start a ${title.toLowerCase()} project`}>→</a></article>)}</div></section>
    <section id="about" className="about-business" data-reveal><div className="about-aside"><span className="kicker">About</span><b>YS</b></div><div><h2>A developer who understands both <em>technology and business.</em></h2><p>I&apos;m Yash, a developer with a professional background in IT and cloud technology. I build websites and software for businesses that need something better than an off-the-shelf solution.</p><p>My approach is simple: understand the business, build what is actually needed, and deliver something fast, reliable, and easy to maintain.</p><a href="#contact" className="text-link">Start a conversation <Arrow /></a></div></section>
    <section className="reasons" data-reveal><div className="section-heading"><div><span className="kicker">Why work with me</span><h2>Practical work, delivered <em>well.</em></h2></div></div><div className="reason-grid">{[["Clear communication", "Straight answers, visible progress, and no unnecessary jargon."], ["Built for every screen", "Mobile-first interfaces that feel right wherever your customers find you."], ["Performance-focused", "Fast, lean development choices that respect your visitors’ time."], ["Easy to maintain", "A clean foundation you can update and grow without starting again."], ["Cost-conscious", "The right level of technology for the job—nothing more than you need."], ["Support after launch", "Help with sensible next steps once your site or product is live."]].map(([title, copy]) => <article key={title}><span>✓</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="process" className="simple-process" data-reveal><div><span className="kicker">A simple process</span><h2>From idea to <em>live.</em></h2></div><ol>{[["01", "Discuss", "Understand the business and requirements."], ["02", "Plan", "Define the right solution and scope."], ["03", "Build", "Develop with regular feedback."], ["04", "Launch", "Test, deploy, and hand over."]].map(([number, title, copy]) => <li key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
    <section id="contact" className="contact-business" data-reveal><div><span className="kicker">Let&apos;s talk</span><h2>Have a project in <em>mind?</em></h2><p>Tell me what you&apos;re building, what you need, and where you&apos;d like to take it.</p><div className="contact-links"><a href="mailto:hello@your-domain.com">Email <Arrow diagonal /></a><a href="https://wa.me/your-number">WhatsApp <Arrow diagonal /></a><a href="https://linkedin.com/in/your-linkedin-username">LinkedIn <Arrow diagonal /></a><a href="https://github.com/your-github-username">GitHub <Arrow diagonal /></a></div></div><div><ContactForm /></div></section>
  </main><Footer /></>;
}
