import Image from "next/image";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Arrow } from "@/components/icons";
import { ContactForm } from "@/components/contact-form";
import { ScrollEffects } from "@/components/scroll-effects";
import { WorkShowcase } from "@/components/work-showcase";
import { Atmosphere } from "@/components/atmosphere";

const services = [["⌘", "Website Development", "Professional websites that build trust and turn visitors into enquiries."], ["▣", "Web Applications", "Custom tools for bookings, dashboards, workflows, and customer experiences."], ["⌑", "E-commerce", "Online stores built around product discovery, clear checkout, and growth."], ["◫", "Custom Software", "Purpose-built software for the processes off-the-shelf tools do not solve."], ["⌁", "APIs & Integrations", "Connect payments, platforms, and the services your business already uses."], ["◌", "IT & Cloud", "Practical deployment, integrations, and cloud support when it matters."]];
const traits = [["⌘", "Clean code", "Maintainable and scalable"], ["↯", "Fast performance", "Optimized for speed"], ["▯", "Mobile first", "Built for every screen"], ["◇", "Reliable", "Designed to last"]];

export default function Home() { const jsonLd = { "@context": "https://schema.org", "@type": "ProfessionalService", name: "Yash", description: "Website, web application, and custom software development for businesses.", email: "yashkhiraiya1@gmail.com", areaServed: "Worldwide" };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Navbar /><main className="premium-home"><ScrollEffects />
    <section id="home" className="premium-hero"><Atmosphere /><div className="premium-hero-inner"><div className="premium-hero-copy" data-reveal><span className="hero-pill"><i /> Building digital solutions</span><h1>Websites &amp; software <em>for real businesses.</em></h1><p>I design and develop modern websites, web applications, and custom digital solutions that are fast, practical, and easy to use.</p><div className="hero-actions"><a href="#contact" className="button accent-button">Start a project <span>→</span></a><a href="#work" className="button ghost-button">View my work <span>→</span></a></div></div><div className="hero-devices" data-reveal><div className="laptop"><div className="laptop-screen"><Image src="/projects/event-platform.webp" alt="Event platform website shown inside a laptop mockup" fill priority sizes="(max-width: 760px) 90vw, 650px" /></div><i className="laptop-base" /></div><div className="phone"><div className="phone-screen"><Image src="/projects/booking-platform.webp" alt="Booking application shown inside a phone mockup" fill priority sizes="180px" /></div></div><span className="hero-scribble">Build<br />with clarity ↗</span></div></div><div className="hero-capabilities"><span><i>▣</i> Websites</span><span><i>⌘</i> Web apps</span><span><i>⌑</i> E-commerce</span><span><i>◫</i> Custom software</span><p>Modern · Fast · Reliable · Built to grow</p></div></section>
    <section id="services" className="premium-services" data-reveal><div className="section-shell"><div className="premium-section-head"><div><span className="eyebrow-dark">Services</span><h2>What I build</h2><p>Practical digital solutions to help your business grow.</p></div><p>From simple websites to complex applications, I focus on building what you actually need.</p></div><div className="premium-service-grid">{services.map(([icon, title, copy], index) => <article key={title}><div><span className="service-icon">{icon}</span><small>0{index + 1}</small></div><h3>{title}</h3><p>{copy}</p><a href="#contact" aria-label={`Discuss ${title}`}>→</a></article>)}</div></div></section>
    <WorkShowcase />
    <section id="about" className="premium-about" data-reveal><div className="section-shell about-shell"><div className="about-visual"><div className="about-monogram">Y</div><div className="availability"><i /> Available for new projects</div><span>YASH / SOFTWARE DEVELOPER</span></div><div className="about-copy"><span className="eyebrow-dark">About me</span><h2>Hi, I&apos;m Yash.</h2><h3>A developer who turns ideas into real, working products.</h3><p>I have a professional background in IT and cloud technology. I build websites and software for businesses that need something better than an off-the-shelf solution.</p><p>My approach is simple: understand the problem, build what is actually needed, and deliver something fast, reliable, and easy to maintain.</p><a href="#contact" className="outline-link">More about me <Arrow /></a></div><div className="about-traits">{traits.map(([icon, title, copy]) => <article key={title}><span>{icon}</span><h4>{title}</h4><p>{copy}</p></article>)}</div></div></section>
    <section id="process" className="premium-process" data-reveal><div className="section-shell"><span className="eyebrow-dark">A simple process</span><h2>From an idea to a product that works.</h2><ol>{[["01", "Discuss", "Understand the business and what you need."], ["02", "Plan", "Define the right solution and scope."], ["03", "Build", "Develop with clear, regular feedback."], ["04", "Launch", "Test, deploy, and hand over."]].map(([number, title, copy]) => <li key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
    <section id="contact" className="premium-contact"><Atmosphere className="contact-atmosphere" /><div className="premium-contact-inner" data-reveal><span>Let&apos;s work together</span><h2>Have a project in mind?</h2><p>Tell me what you&apos;re building, what you need, and where you&apos;d like to take it.</p><div className="hero-actions"><a href="mailto:yashkhiraiya1@gmail.com" className="button accent-button">Start a conversation <span>→</span></a><a href="#work" className="button ghost-button">View my work <span>→</span></a></div><div className="premium-contact-form"><ContactForm /></div></div></section>
  </main><Footer /></>;
}
